AGL.Presentation/Models/Cat.cs
using System;
using System.Collections.Generic;
using System.Text;

namespace AGL.Presentation.Models
{
    public class Cat
    {
        public string Name { get; set; }
    }
}

AGL.Presentation/Models/Error.cs
using System;
using System.Collections.Generic;
using System.Text;

namespace AGL.Presentation.Models
{
    public class Error
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AGL.Presentation/Models/Gender.cs
using AGL.Dto;
using System;
using System.Collections.Generic;
using System.Text;

namespace AGL.Presentation.Models
{
    public class Gender
    {
        public GenderTypeEnum GenderType { get; set; }
        public List<Cat> Cats { get; set; }
    }
}

AGL.Presentation/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AGL.BusinessLogic;
using AGL.Dto;
using AGL.Library;
using AGL.Presentation.Models;
using Microsoft.AspNetCore.Mvc;

namespace AGL.Presentation.Controllers
{
    public class PeopleController : Controller
    {
        private IPeopleBusinessLogic _peopleBusinessLogic { get; }

        public PeopleController(IPeopleBusinessLogic peopleBusinessLogic)
        {
            _peopleBusinessLogic = peopleBusinessLogic;
        }

        /// <summary>
        /// Gets a list of people from the business layer in the correct view structure.
        /// </summary>
        public async Task<IActionResult> Index()
        {
            try
            {
                var peopleResponse = await _peopleBusinessLogic.GetPeople();
                if (peopleResponse.ResponseStatus == ResponseStatusEnum.Failure)
                {
                    peopleResponse.Errors.ForEach(error =>
                    {
                        ModelState.AddModelError("", error);
                    });

                    return View(new List<Gender>());
                }
                else
                {
                    var viewModel = peopleResponse.Data.Select(gender => new Gender
                    {
                        GenderType = gender.Gender,
                        Cats = gender.Cats.Select(cat => new Cat
                        {
                            Name = cat.Name
                        }).ToList()
                    }).ToList();

                    return View(viewModel);
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.Message);
                return View(new List<Gender>());
            }
        }

        /// <summary>
        /// Returns contact details from the razor view
        /// </summary>
        public IActionResult Contact()
        {
             return View();
        }
        
        public IActionResult Error()
        {
            return View(new Error { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AGL.Presentation/Views/People/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>Sunil Kumar</h3>

<ul>
    <li><strong>Mobile:</strong> <a href="tel:0410862890">0410862890</a></li>
    <li><strong>Email:</strong> <a href="mailto:dsunil75@live.com">dsunil75@live.com</a></li>
</ul>

AGL.Presentation/Views/People/Index.cshtml
@model List<Gender>
@{
    ViewData["Title"] = "Cat names grouped by owners gender";
}
<h2>@ViewData["Title"]</h2>

@foreach (var gender in Model)
{
    <h4>@gender.GenderType</h4>
    <ul>
        @foreach (var cat in gender.Cats)
        {
            <li>@cat.Name</li>
        }
    </ul>
}

@Html.ValidationSummary(true, "", new { @class = "text-danger" })

AGL.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AGL Coding Test</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="People" asp-action="Index" class="navbar-brand">AGL Coding Test</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="People" asp-action="Index">People</a></li>
                    <li><a asp-area="" asp-controller="People" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>AGL Coding Test</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>